/**
 * Type declarations for missing Material UI icons
 * Updated to include sx prop support for all icon components
 */

declare module "@mui/icons-material" {
  import { SxProps } from '@mui/system';
  import { Theme } from '@mui/material/styles';
  import * as React from "react";

  // Missing icons used in the application
  export const DeviceHub: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const BugReport: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Build: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Apartment: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const VerifiedUser: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Security: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Shield: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const BugReportOutlined: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Search: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Visibility: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const VisibilityOff: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Dashboard: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Settings: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Assessment: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Assignment: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ListAlt: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const DateRange: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Today: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Event: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const EventNote: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const CalendarToday: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Warning: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Error: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Info: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const CheckCircle: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ArrowUpward: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ArrowDownward: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ArrowForward: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ArrowBack: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Refresh: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Add: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Edit: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Delete: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Save: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Cancel: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Close: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Menu: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const MoreVert: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Description: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Email: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Mail: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>; // Alias for Email
  export const Person: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Lock: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Login: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const LockReset: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const PhoneAndroid: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const QrCode: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Brightness4: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Brightness7: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Api: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const LockOpen: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const AccountCircle: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ExitToApp: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Notifications: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const NotificationsActive: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const NotificationsNone: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const FilterList: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Sort: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Print: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const GetApp: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ExpandMore: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ExpandLess: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Download: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Upload: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const AttachFile: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const CloudUpload: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const CloudDownload: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const FolderOpen: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Folder: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const NetworkWifi: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Wifi: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const WifiOff: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Computer: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Storage: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Memory: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Send: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const FiberManualRecord: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const HelpOutline: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Help: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Forum: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Chat: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Timeline: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Link: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const FormatQuote: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Comment: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const AutoGraph: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const PictureAsPdf: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const TableChart: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ShieldOutlined: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const FindInPage: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const MonetizationOn: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ShieldRounded: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const BarChart: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const SecurityUpdate: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Share: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ContentCopy: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Public: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Check: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Lock: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  
  // Add missing icons from error list
  export const People: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const PersonAdd: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const FileCopy: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const GridView: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const FormatListBulleted: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const DragIndicator: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Fullscreen: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const WatchLater: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const SupportAgent: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const AccessTime: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const PhishingOutlined: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Router: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Speed: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const UploadFile: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Sensors: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const SignalWifi4Bar: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const AutoFixHigh: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Pause: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Autorenew: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Backup: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ManageAccounts: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Radar: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const ShowChart: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const StackedBarChart: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const DonutLarge: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const FileDownload: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const CloudQueue: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const QueryStats: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const SyncProblem: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const WarningAmber: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Logout: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
  export const Update: React.ComponentType<React.SVGProps<SVGSVGElement> & { sx?: SxProps<Theme> }>;
}
